### ISSUE TITLE
flutter web crash

### ISSUE THREAD

**Issue by sgehrman** [vi-k/bubble#20]
Works until I scroll, then I get this:

Exception has occurred.
"Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/clip.dart:295:12
_clipElement == null
is not true
    at Object.throw_ [as throw] (http://localhost:35885/dart_sdk.js:4324:11)
    at Object.assertFailed (http://localhost:35885/dart_sdk.js:4271:15)
    at _engine.PersistedPhysicalShape.new.[_applyShape] (http://localhost:35885/dart_sdk.js:152323:47)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:35885/dart_sdk.js:152362:26)
    at _engine.PersistedOffset.new.[_updateManyToMany] (http://localhost:35885/dart_sdk.js:151083:22)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:150918:32)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:152749:13)
    at _engine.PersistedClipRect.new.[_updateManyToMany] (http://localhost:35885/dart_sdk.js:151083:22)
    at _engine.PersistedClipRect.new.update (http://localhost:35885/dart_sdk.js:150918:32)
    at _engine.PersistedClipRect.new.update (http://localhost:35885/dart_sdk.js:152040:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:35885/dart_sdk.js:151035:18)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:150914:31)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:152749:13)
    at _engine.PersistedTransform.new.[_updateManyToMany] (http://localhost:35885/dart_sdk.js:151075:20)
    at _engine.PersistedTransform.new.update (http://localhost:35885/dart_sdk.js:150918:32)
    at _engine.PersistedTransform.new.update (http://localhost:35885/dart_sdk.js:163555:13)
    at _engine.PersistedPhysicalShape.new.[_updateManyToMany] (http://localhost:35885/dart_sdk.js:151075:20)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:35885/dart_sdk.js:150918:32)
    at _engine.PersistedPhysicalShape.new.update (http://localhost:35885/dart_sdk.js:152350:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:35885/dart_sdk.js:151013:18)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:150914:31)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:152749:13)
    at _engine.PersistedOffset.new.[_updateManyToOne] (http://localhost:35885/dart_sdk.js:151013:18)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:150914:31)
    at _engine.PersistedOffset.new.update (http://localhost:35885/dart_sdk.js:152749:13)
    at _engine.PersistedTransform.new.[_updateManyToOne] (http://localhost:35885/dart_sdk.js:151013:18)
    at _engine.PersistedTransform.new.update (http://localhost:35885/dart_sdk.js:150914:31)
    at _engine.PersistedTransform.new.update (http://localhost:35885/dart_sdk.js:163555:13)
    at _engine.PersistedScene.new.[_updateManyToOne] (http://localhost:35885/dart_sdk.js:151013:18)
    at _engine.PersistedScene.new.update (http://localhost:35885/dart_sdk.js:150914:31)
    at http://localhost:35885/dart_sdk.js:163301:33

**Comment by vi-k** [comment]
Please, check it again.
